### ISSUE TITLE
LCU bug

### ISSUE THREAD

**Issue by TimWeaving** [UCL-CCS/symmer#135]
Minimal code to reproduce the bug:
![image](https://user-images.githubusercontent.com/72549389/234733058-c476f9d6-e057-416a-aa5d-f6d0cea03653.png)
Note the zero coefficient on the second rotation - this was causing one of the bugs in ContextualSubspace as the contextual operator was being mapped to zero.

**Comment by AlexisRalli** [comment]
Issue fixed in pull reqest #142
