### ISSUE TITLE
Update python requirements 

### ISSUE THREAD

**Issue by MIWdlB** [UCL-CCS/symmer#162]
Currently Symmer has quite tight restrictions on python version:

```
[tool.poetry.dependencies]
python = ">=3.8 <3.11"
```

I'm going to suggest updating this to allow newer python versions to be included in the versioning (and then make it easier to use symmer in Nbed)

`python = "^3.8"`

**Comment by MIWdlB** [comment]
This is blocked by Qubovert, which I tried tp update myself but its a bit of a mess.

**Comment by AlexisRalli** [comment]
Solved in pull request #178
